### ISSUE TITLE
Slider does not work with dynamically generated HTML??

### ISSUE THREAD

**Issue by AddiJamshidi1** [equinox7/lbSlider#1]
I have a jQuery plugin which takes a HTML div element and generates the ul li span img snippet to it. The generated snippet looks something like this:

After above is generated by my plugin and added to the <div> element, I then run the lbSlider plugin on this div element. And it does not work.
If, however, I hard code the exact same generated snippet HTML code , it works fine.

Please advise as how I can make this work.
Thank you so kindly,

Email: AddiJamshidi@gmail.com

P.S - Below please find my code:

```
<script type="text/javascript">
    $(document).ready(function() {

        $("#listOfClusters").clusterViewList({
            clusterSelectedHandler : function(event, data) {
                alert("clusterSelected was call with data=" + data)
            }
        });
        // after above plugin is finished the #listOfClusters div element has a <ul> element with about 6-7 <li> elements each holding an <img> element.  Calling lvlSlider does not work in this case. However if I hard code the same exact generated snippet code manually under #listofClusters div element, it works just fine.
        $("#listOfClusters").lbSlider({
            leftBtn : '.sa-left',
            rightBtn : '.sa-right',
            visible : 5,
            autoPlay : true,
            autoPlayDelay : 5
        });
    });
</script>

<div class="slider-wrap">
```

<div id="listOfClusters" class="slider">

</div>

<a href="#" class="slider-arrow sa-left">&lt;</a> 
<a href="#" class="slider-arrow sa-right">&gt;</a> 
</div>

**Comment by Developer-Amit** [comment]
Hey I have same problem.... Please view this..
/// This Is Ajax Dynamic HTML Generation Code////////

jQuery.ajax({
    url: "http://ec2-52-21-208-137.compute-1.amazonaws.com:5000/api/v1/mobile/videos/" + catname + "/" + appid,
    type: "GET",
    data: {
        'category': catname
    },
    dataType: 'json',
    success: function(response) {
        var cat_name = catname.replace(/\s/g, "_");
        console.log(cat_name);
        var str = "<div class='col-lg-12 col-md-12 " + cat_name + "'><h4><a class='head-title' href='#'>" + catname + "</a></h4><a class='see-more' href='#'>View More</a></div><div class='col-lg-12 col-md-12'><button type='button' class='slick-prev'>Previous</button><ul id='slide_content' class='vm-videolist'>";
        $.each(response, function(index, val) {
            source = val.isYoutube == true ? 'y-' + val.viemoId : 'v-' + val.viemoId;
            str += "<li class=" + li_id + "><div class='vm-video-thumb'><a  class='video-link'> <img width='300' height='110' class='img-responsive' data-video-id=" + source + " src=" + val.videoThumbLink + "></a><span class='vm-duration'></span> <span class='reward-points'>" + val.watchingRewardPoints + " Points </span><div class='vm-thumb-overlay'><div class='hover-icons'><a href='video.html?id=" + val._id + "' class='video-popup-btn' > <span class='play-btn'><i class='ion-play'></i></span></a></div></div></div><div class='vm-video-info'><div class='title'><h3><a href='video.html?id=" + val._id + "'>" + val.title + "</a></h3></div><div class='author'> <a href='#''>" + val.tags + "</a> </div><div class='views-date'> <span class='views'>" + val.viewCount + " Views</span> <span class='date'>1 day ago</span> </div></div></li>";
        });
        str += "</ul><button type='button' class='slick-next'>Next</button></div>";
        $("#vm-videolist").append(str);
    },
    complete: function() {
        //console.log('on completed');
    },
    error: function(xhr) { // if error occured
        var str = '<li>Error occured please check category </li>';
        $('#videos').append(str);
    },
});

/////I have make this code for slider/////
$('#slide_content').slick({
            dots: true,
            infinite: false,
            speed: 300,
            slidesToShow: 4,
            slidesToScroll: 4,
});



<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick-theme.css"/>

<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
