### ISSUE TITLE
How to show with out visible{for ex : visible: 2 - avoid this line code} Images or content ?

### ISSUE THREAD

**Issue by baladkb** [equinox7/lbSlider#5]
First : I am using **lbSlider** in my app. 
I'm  set value of visible elements quantity 2(visible: 2) and to set 2 li block it works fine, but I'm increasing or decreasing  the content means it not show the all content, it hides the some of the content,

please provide any suggesting, it improve the **lbSlider Quality** also

**Comment by equinox7** [comment]
You mean, you want to change slider options dynamically by adding/removing/modifying its content ?

**Comment by baladkb** [comment]
@equinox7 yes.

**Comment by cletter7** [comment]
There is no solution for dynamically changing slider contents at the moment.

**Comment by cletter7** [comment]
You can try using another slider. For example [Slick](http://kenwheeler.github.io/slick/). It has methods for adding and removing slides dynamically, after slider initialization.

**Comment by baladkb** [comment]
@equinox7 thanks.
